### PR TITLE
Rudimentary support for string ranges

### PR DESCRIPTION
**Pull request by prakashk**
Ranges should support string ranges too. Just basic stuff. Doesn't handle mixed type ranges like `1 .. "5"`.

Still learning Scala, it is probably completely non-idiomatic, so feel free to improve it.

### CODE REVIEW

**Comment by stevan** [comment]
Prakash this is not merging in cleaning to master, can you please rework the commit so that it will merge in cleanly? Thanks, Stevan

**Comment by prakashk** [comment]
I am not sure what you mean by "rework". Could you elaborate on what the problem was?

Actually, I'd like you to hold off on this one. I am looking at the documentation for the range operator (perlop), and I will need to make more changes even to call it "rudimentary" support. I will update the request when I am done.

**Comment by stevan** [comment]
Prakash,

If you look at this pull request, it says "cannot be automatically merged" this is likely because there are conflicts in the merge. You should be able to resolve these conflicts by merging master back into your branch, resolve any conflicts, then re-issue the pull request, at which point it should just work.

If you want to wait on this though, that is fine.
- Stevan

**Comment by jasonmay** [comment]
Hi Prakash,

runtime-improvements is a branch that is out-of-date, which is causing the un-clean merge. Could you re-play these on to a new branch (made off master)?

Thanks!
Jason

**Comment by prakashk** [comment]
Hi Jason,

I just finished merging master into my local copy of runtime-improvements, and resolved conflicts. Should I go ahead with committing and pushing these changes (about 50 files!)? Or, is it preferred to make my changes to a new branch of 'master'?

Thanks,
Prakash

**Comment by prakashk** [comment]
I created a new branch prakashk/string-ranges off of master, and applied my changes to that branch. Should I create a new pull request? Or, is there a way this one can be reused?

**Comment by stevan** [comment]
Prakash, 

Please make a new pull request, this one won't transfer.

Thanks again for the work!
- Stevean

**Comment by prakashk** [comment]
Replaced by https://github.com/MoeOrganization/moe/pull/56

**Pull request closed without merging**
