### PR TITLE
Array slicing by range/another array and other stuff

### PR DESCRIPTION
**Pull request by prakashk**

### CODE REVIEW

**Comment by stevan** [comment]
Excellent!

**Comment by stevan** [comment]
I would really like to move these 99-problems into Test::More style tests

**Comment by prakashk** [comment]
Yeah. I am going to convert them soon.

**Comment by stevan** [comment]
@prakashk excellent, I would love to have those as tests too. Please put them in the t/099-problems/ directory so we can run them easily as a group.

**Pull request merged**
