### PR TITLE
Various things

### PR DESCRIPTION
**Pull request by prakashk**
- replace "\n" with system property so test runs on all platforms
- array.first should return undef when no element satisfies the predicate
- hash.eqv method + tests
- Looks like parser doesn't need the class sigil any more.
- Do not create new scope for each line of code in REPL. (there might be a better way to do this?)

### CODE REVIEW

**Comment by stevan** [comment]
@prakashk could you remake this pull request but leave out the "Do not create new scope ..." commit, I am not sure that I like that approach.

Thanks,

Stevan

**Comment by prakashk** [comment]
@stevan: I wan't totally sure about that either. My first approach was even worse :-)

I don't see a quick way to remove commits from a pull request or choosing specific commits to create a pull request (github adds all commits in the branch to the request). Using my limited experience with git, I can only think of creating a new branch off master, apply all commits but this one, and push this new branch to create a new pull request. Got any better ideas?

Thanks,
prakash

**Comment by stevan** [comment]
@prakashk sorry, no better ideas no. But it should be easy enough to just cherrypick the 7 commits into a new branch

**Comment by prakashk** [comment]
@stevan: new pull request https://github.com/MoeOrganization/moe/pull/103

Closing this one.

**Pull request closed without merging**
