### PR TITLE
make single assignment a BinOp with "=" as the operator

### PR DESCRIPTION
**Pull request by prakashk**
multiple assignment still to do.

Addressing Issue #92.

### CODE REVIEW

**Comment by prakashk** [comment]
There are a couple of lines in MoeProductions.scala that don't belong in this commit, but they would be in anyway when I merge the regex branch. So, I didn't bother to remove them.

**Comment by stevan** [comment]
@prakashk - this pull request actually broke the `use` statement, I suspect you have the fix in your regexp branch already and it just didn't make it into this pull request. please note bc0a74820ba87dd6cc21d825bcb2b38cfc82b3ea where I fixed it for master.

**Comment by stevan** [comment]
also, @prakashk++ for burning down the issues list :)

**Comment by prakashk** [comment]
Ugh, sorry about that. I should remember to run tests with prove-moe before pushing changes.

**Comment by stevan** [comment]
@prakashk no worries, it was a simple fix

**Pull request merged**
